__version__ = "0.2.1"
__author__ = "Mirco Huennefeld"
__author_email__ = "mirco.huennefeld@tu-dortmund.de"
__description__ = "Collection of TF functions and helpful additions"
__url__ = "https://github.com/mhuen/TFScripts"
